[project]
name = "sophos-firewall-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.12.0",
    "pydantic-settings>=2.11.0",
    "rich>=14.2.0",
    "sophosfirewall-python>=0.1.65",
]
